SELECT 
  ,TOP 1000 
  ,NodeID
  ,ObjectSubType
  ,IPAddress
  ,IPAddressType
  ,DynamicIP
  ,Caption
  ,NodeDescription
  ,Description
  ,DNS
  ,SysName
  ,Vendor
  ,SysObjectID
  ,Location
  ,Contact
  ,VendorIcon
  ,Icon
  ,Status
  ,PolledStatus
  ,StatusLED
  ,StatusDescription
  ,NodeStatusRootCause
  ,NodeStatusRootCauseWithLinks
  ,CustomStatus
  ,IOSImage
  ,IOSVersion
  ,GroupStatus
  ,StatusIcon
  ,LastBoot
  ,SystemUpTime
  ,ResponseTime
  ,PercentLoss
  ,AvgResponseTime
  ,MinResponseTime
  ,MaxResponseTime
  ,CPUCount
  ,CPULoad
  ,MemoryUsed
  ,LoadAverage1
  ,LoadAverage5
  ,LoadAverage15
  ,MemoryAvailable
  ,PercentMemoryUsed
  ,PercentMemoryAvailable
  ,LastSync
  ,LastSystemUpTimePollUtc
  ,MachineType
  ,IsServer
  ,Severity
  ,UiSeverity
  ,ChildStatus
  ,Allow64BitCounters
  ,AgentPort
  ,TotalMemory
  ,CMTS
  ,CustomPollerLastStatisticsPoll
  ,CustomPollerLastStatisticsPollSuccess
  ,SNMPVersion
  ,PollInterval
  ,EngineID
  ,RediscoveryInterval
  ,NextPoll
  ,NextRediscovery
  ,StatCollection
  ,External
  ,Community
  ,RWCommunity
  ,IP
  ,IP_Address
  ,IPAddressGUID
  ,NodeName
  ,BlockUntil
  ,BufferNoMemThisHour
  ,BufferNoMemToday
  ,BufferSmMissThisHour
  ,BufferSmMissToday
  ,BufferMdMissThisHour
  ,BufferMdMissToday
  ,BufferBgMissThisHour
  ,BufferBgMissToday
  ,BufferLgMissThisHour
  ,BufferLgMissToday
  ,BufferHgMissThisHour
  ,BufferHgMissToday
  ,OrionIdPrefix
  ,OrionIdColumn
  ,SkippedPollingCycles
  ,MinutesSinceLastSync
  ,EntityType
  ,DetailsUrl
  ,DisplayName
  ,Category
  ,IsOrionServer
FROM
  Orion.Nodes
